require('packer-config')
--require('colorschemes-config.nightfox')
--require('colorschemes-config.vsc')
--require('colorschemes-config.gruv')
require('colorschemes-config.rasmus')
require('mappings')
require('settings')
require('nvim-tree-config')
require('lsp-config.language-servers')
require('lsp-config.nvim-cmp')
require('lualine-config')
require('barbar-config')
require('autopairs-config')
require('toggleterm-config')
require('indent-blankline-config')
require('copilot-config')
require('treesitter-config')
require('nvim-comment-config')
require('truezen-config')
require('nvim-colorizer-config')


