require('settings')
require('packer-config')
-- to change colorscheme, just change suffix to any other folder in colorschemes-config
require('colorschemes-config.cat')
require('key-maps')
require('nvim-tree-config')
require('lsp-config.language-servers')
require('lsp-config.nvim-cmp')
require('lualine-config')
require('autopairs-config')
require('toggleterm-config')
require('indent-blankline-config')
require('copilot-config')
require('treesitter-config')
require('nvim-comment-config')
require('nvim-colorizer-config')
require('telescope-config')
require('barbar-config')
require('whichkey-config.setup')
require('whichkey-config.registers')
require('dashboard-config')
require('nui-config')
require('rust-config')
require('dapui-config')

