-- function lines_from(file)
--   local lines = {}
--   for line in io.lines(file) do 
--     lines[#lines + 1] = line
--   end
--   return lines
-- end
--
-- local keymaps_file = os.getenv('HOME') .. '/.config/nvim/lua/key-maps/init.lua'
--
-- ---------------------------------------------
--
-- local utils = {}
--
-- utils.spawned_keymaps = false
-- utils.spawned_menu = false
--
-- utils.Popup = require("nui.popup")
-- utils.event = require("nui.utils.autocmd").event
--
-- utils.key_popup = utils.Popup({
-- 	enter = true,
-- 	focusable = true,
-- 	border = {
-- 		style = "rounded",
--     padding = {
--       bottom = 1,
--     },
--     text = {
--       bottom = "Press q to close",
--       bottom_align = "left",
--     }
-- 	},
-- 	position = "50%",
-- 	size = {
-- 		width = "70%",
-- 		height = "50%",
-- 	},
-- 	buf_options = {
-- 		filetype = "lua",
--     modifiable = false,
-- 	}, 
-- })
--
-- -- mount and print to buffer
-- function utils.show_keymaps()
--   if utils.spawned_keymaps == true then
--     utils.key_popup:show()
--   else
--     local keymaps = lines_from(keymaps_file)
--     for k, v in pairs(keymaps) do
--       vim.api.nvim_buf_set_lines(utils.key_popup.bufnr, k - 1, k, false, { v })
--     end
--     utils.key_popup:mount()
--     utils.spawned_keymaps = true
--   end
-- end
--
-- -- close buffer on q press
-- utils.hide_keymaps = utils.key_popup:map("n", "q", function(bufnr)
--   utils.key_popup:hide()
-- end, { noremap = true })
--
-- utils.Menu = require('nui.menu')
--
-- utils.menu = utils.Menu({
--   position = "50%",
--   size = {
--     width = "25%",
--     height = "10%",
--   },
--   border = {
--     style = "rounded",
--     text = {
--       top = "[Choose-a-colorscheme]",
--       top_align = "center",
--       bottom = "Press q to close",
--       bottom_align = "left"
--     },
--   },
--   win_options = {
--     winhighlight = "Normal:Normal,FloatBorder:Normal",
--   },
--   buf_options = {
--     modifiable = false,
--   }
-- }, {
--   lines = {
--     utils.Menu.item("Hydrogen (H)"),
--     utils.Menu.item("Carbon (C)"),
--     utils.Menu.item("Nitrogen (N)"),
--     utils.Menu.item("Helium (He)"),
--     utils.Menu.item("Neon (Ne)"),
--     utils.Menu.item("Argon (Ar)"),
--   },
--   max_width = 20,
--   keymap = {
--     focus_next = { "j", "<Down>", "<Tab>" },
--     focus_prev = { "k", "<Up>", "<S-Tab>" },
--     close = { "q", "<C-c>" },
--     submit = { "<CR>", "<Space>" },
--   },
--   on_submit = function(item)
--     vim.cmd[[colorscheme everblush]]
--   end,
-- })
--
-- function utils.show_menu()
--   if spawned_menu == true then
--     utils.menu:show()
--   else
--     utils.menu:mount()
--     spawned_menu = true
--   end
-- end
--
-- return utils
